apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sample-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sample-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-frontend
