apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-frontend
automountServiceAccountToken: false
