apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-workload
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: ${KEY_VAULT_WORKLOAD_IDENTITY_CLIENT_ID}
  labels:
    azure.workload.identity/use: "true"
