apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-connection
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: postgresql-connection
    creationPolicy: Owner
  data:
    - secretKey: connection-string
      remoteRef:
        key: postgresql-connection-string
