apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-app
resources:
  - ../../base
images:
  - name: sample-backend
    newName: registry.invalid/sample-backend
    newTag: bootstrap
  - name: sample-frontend
    newName: registry.invalid/sample-frontend
    newTag: bootstrap
